# auto-generated by auto.pl

$b/compat.o: src/compat.c src/coho.h

$b/compat.o:
	@mkdir -p ${@D}
	${CC} ${CFLAGS} ${CFLAGS_COMPAT} -c -o $@ src/compat.c

$b/libcoho.a: $b/compat.o

$b/smiles.o: src/smiles.c src/coho.h

$b/smiles.o:
	@mkdir -p ${@D}
	${CC} ${CFLAGS} ${CFLAGS_SMILES} -c -o $@ src/smiles.c

$b/libcoho.a: $b/smiles.o

$b/python/coho/__init__.c: python/coho/__init__.pyx
	@mkdir -p ${@D}
	${CYTHON} ${CYTHON_FLAGS} ${CYTHON_FLAGS.__INIT__} -Ipython -o $@ python/coho/__init__.pyx

$b/python/coho/__init__.o: $b/python/coho/__init__.c
	${CC} ${CFLAGS_PY} ${CFLAGS_PY.__INIT__} -Isrc -o $@ -c $b/python/coho/__init__.c

$b/python/coho/__init__.so: $b/python/coho/__init__.o $b/libcoho.a
	${CC} -shared -o $@ $b/python/coho/__init__.o $b/libcoho.a

$b/python/coho/__init__.pyi: python/coho/__init__.pyi
	@mkdir -p ${@D}
	install -m0644 python/coho/__init__.pyi $@

py.c += $b/python/coho/__init__.c

py.o += $b/python/coho/__init__.o

py.so += $b/python/coho/__init__.so

py.pyi += $b/python/coho/__init__.pyi

py.obj += $b/python/coho/__init__.c
py.obj += $b/python/coho/__init__.o
py.obj += $b/python/coho/__init__.so
py.obj += $b/python/coho/__init__.pyi

$b/python/coho/smiles.c: python/coho/smiles.pyx
	@mkdir -p ${@D}
	${CYTHON} ${CYTHON_FLAGS} ${CYTHON_FLAGS.SMILES} -Ipython -o $@ python/coho/smiles.pyx

$b/python/coho/smiles.o: $b/python/coho/smiles.c
	${CC} ${CFLAGS_PY} ${CFLAGS_PY.SMILES} -Isrc -o $@ -c $b/python/coho/smiles.c

$b/python/coho/smiles.so: $b/python/coho/smiles.o $b/libcoho.a
	${CC} -shared -o $@ $b/python/coho/smiles.o $b/libcoho.a

$b/python/coho/smiles.pyi: python/coho/smiles.pyi
	@mkdir -p ${@D}
	install -m0644 python/coho/smiles.pyi $@

py.c += $b/python/coho/smiles.c

py.o += $b/python/coho/smiles.o

py.so += $b/python/coho/smiles.so

py.pyi += $b/python/coho/smiles.pyi

py.obj += $b/python/coho/smiles.c
py.obj += $b/python/coho/smiles.o
py.obj += $b/python/coho/smiles.so
py.obj += $b/python/coho/smiles.pyi
