version: 2.1
jobs:

  build-and-test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          command: |
            sudo pip install cython
            make
            make python.wheel
            make test

  build-manylinux1:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
      - checkout
      - run: ci/python-build-manylinux1-wheels

workflows:
  version: 2

  build-and-test:
    jobs:
      - build-and-test
      - build-manylinux1
