#!/bin/bash
set -e -x

cd $(dirname $0)/..

for minor in 8 7 6 5; do
    bin=(/opt/python/cp3$minor*/bin)
    [ -d $bin ] || continue

    b="$PWD/build-$minor"

    $bin/pip install cython

    PATH=$bin:$PATH make BUILD_DIR=$b python.stage

    $bin/pip wheel -w $b/wheelhouse $b/python
    auditwheel repair -w $b/wheelhouse $b/wheelhouse/*
    rm -f $b/wheelhouse/*-linux_*
    $bin/pip install --no-index -f $b/wheelhouse coho
    (cd $HOME; $bin/python -c "import coho.smiles")
done
